### ISSUE TITLE
conv_bias_relu fusion slows down inception_v3 batch size of 2

### ISSUE THREAD

**Issue by mei-ye** [ROCmSoftwarePlatform/AMDMIGraphX#143] opened 2018-12-20 20:30 UTC
inception v3 batch size of 2 has about 2X slow -down with fusion.  I discovered this while I was working on stream-scheduling task and had to temporarily disable fusion.

To get the .onnx file, use Mev's instructions:
https://github.com/mvermeulen/migraphx_onnx

In specific, I used the following script to create .onnx file.
import torch
import torchvision.models as models

batch_size = 2

inception = models.inception_v3(pretrained=True)
inception.eval()
torch.onnx.export(inception, torch.randn(batch_size,3,299,299), "inception.onnx")

**Comment by mvermeulen** [comment] 2019-02-11 18:41
Not sure on the causes, but using HCC_PROFILE=2 and then rpt on perf_onnx (minus the compile step and minus the individual instruction timing); suggests that there might also be a "mis-tuned" situation for batch size 2 relative to batch size 4.

I've attached files but item that stands out is the kernel "gcnAsmConv1x1U" which takes 12x longer in batch size 2 than in batch size 4 - and hence dominates 60% of the batch size 2 time and is only 10% of the batch size 4 time.

[inceptionv3i4.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2852512/inceptionv3i4.txt)
[inceptionv3i2.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2852513/inceptionv3i2.txt)

Running a MIOPEN_FIND_ENFORCE=3 tuning on the batch size 2 to see if this speeds up this case.

**Comment by mvermeulen** [comment] 2019-02-11 22:16
After tuning, with MIOPEN_FIND_ENFORCE, the speed for inceptionv3 batch size goes from 55 images/sec to 177 images/sec.

This now fits between batch size 1 (164 images/sec) and batch size 4 (222 images/sec), but will also try tuning inceptionv3 to see if that also speeds up.

The tuning added the following entries on my Vega64 system
'''
48-35-35-5x5-64-35-35-2-2x2-1x1-1x1-0-NCHW-FP32-F=ConvOclDirectFwd:16,16,16,32,1,2,4,4,2;ConvOclDirectFwdFused:8,32,16,32,2,1,4,4,2
192-35-35-1x1-32-35-35-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvActivAsm1x1U:1,16,1,16,1,4;ConvAsm1x1U:1,8,1,16,1,4,2,1;ConvOclDirectFwd1x1:1,\
64,1,1,1,1,16,2048,0
256-35-35-1x1-64-35-35-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvActivAsm1x1U:1,16,1,32,1,4;ConvAsm1x1U:1,8,1,32,1,4,2,1;ConvOclDirectFwd1x1:1,\
64,1,1,1,1,16,2048,0
256-35-35-1x1-48-35-35-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvActivAsm1x1U:1,16,1,32,1,4;ConvAsm1x1U:1,8,1,32,1,4,2,1;ConvOclDirectFwd1x1:1,\
64,1,1,1,0,32,64,0
288-35-35-1x1-64-35-35-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvActivAsm1x1U:1,16,1,32,1,4;ConvAsm1x1U:1,8,1,32,1,4,2,1;ConvOclDirectFwd1x1:1,\
64,1,1,1,1,16,64,0
288-35-35-1x1-48-35-35-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvActivAsm1x1U:1,16,1,32,1,4;ConvAsm1x1U:1,8,1,64,1,4,2,1;ConvOclDirectFwd1x1:1,\
64,1,1,1,1,32,64,0
288-35-35-3x3-384-17-17-2-0x0-2x2-1x1-0-NCHW-FP32-F=ConvOclDirectFwd:32,8,32,32,1,4,4,1,1
96-35-35-3x3-96-17-17-2-0x0-2x2-1x1-0-NCHW-FP32-F=ConvOclDirectFwd:32,8,32,32,1,4,2,1,2
768-17-17-1x1-192-17-17-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:2,8,2,32,1,4,4,2;ConvOclDirectFwd1x1:1,64,1,1,1,4,16,128,0
768-17-17-1x1-128-17-17-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:2,8,2,32,1,4,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,0,16,128,0
768-17-17-1x1-160-17-17-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:2,8,2,32,1,4,4,2;ConvOclDirectFwd1x1:1,64,1,1,1,4,16,128,0
192-17-17-3x3-320-8-8-2-0x0-2x2-1x1-0-NCHW-FP32-F=ConvOclDirectFwd:8,8,8,8,1,1,1,4,2
192-17-17-3x3-192-8-8-2-0x0-2x2-1x1-0-NCHW-FP32-F=ConvOclDirectFwd:8,8,8,8,1,1,1,4,2
1280-8-8-1x1-320-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,1,64,1,4,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,4,16,128,0
1280-8-8-1x1-384-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,1,64,1,4,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,4,16,128,0
1280-8-8-1x1-448-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,1,64,1,4,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,0,16,128,0
1280-8-8-1x1-192-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,1,64,1,2,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,1,16,128,0
2048-8-8-1x1-320-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,1,32,1,4,4,2;ConvOclDirectFwd1x1:1,64,1,1,1,4,16,128,0
2048-8-8-1x1-384-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,2,16,1,2,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,4,16,128,0
2048-8-8-1x1-448-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,2,16,1,4,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,1,16,128,0
2048-8-8-1x1-192-8-8-2-0x0-1x1-1x1-0-NCHW-FP32-F=ConvAsm1x1U:1,8,1,16,1,4,4,1;ConvOclDirectFwd1x1:1,64,1,1,1,1,16,128,0
'''

**Comment by mvermeulen** [comment] 2019-02-12 21:21
Further investigation shows that batch size 2 was missing for both inceptionv3 and inceptionv4 and that MIOpen is tuned for other batch sizes.  The increase in performance when fusion is disabled, may likely be an artifact of untuned kernels.

**Comment by mvermeulen** [comment] 2019-03-06 20:25
Tuning, closing.

**Closed by mvermeulen** 2019-03-06 20:25 UTC
