### ISSUE TITLE
Add support for INT8

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#139] opened 2018-12-12 19:07 UTC

**Comment by scxiao** [comment] 2019-06-12 18:39
This feature is functionally working, but performance is not good because of lower level support.

**Comment by scxiao** [comment] 2019-06-12 20:35
Also, we want the output data type of int8 convolution to be int32, but it outputs float now, we just add an addition convert operator to output the int32 type. Right now, we are waiting for the MIOpen to output int32 data type, then we can remove the convert operator.

Move this issue to 0.4 release.

**Comment by scxiao** [comment] 2019-08-22 19:05
duplicate of issue #270, so close this one.

**Closed by scxiao** 2019-08-22 19:05 UTC
