### ISSUE TITLE
an error: Shapes are not in standard layout

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#852] opened 2021-06-05 01:00 UTC
I use a model to do inference,but an error occurs. the output:
amdmigraphx/src/include/migraphx/check_shapes.hpp:136: standard: softmax: Shapes are not in standard layout

the model link: https://pan.baidu.com/s/1BZ32JKuSt3r0VUZfTgM5Dw 
password：lz2l

**Comment by scxiao** [comment] 2021-06-16 04:54
I tried the latest develop branch, it works well. Could you please try again?

**Comment by qianqing13579** [comment] 2021-06-16 06:44
@scxiao ，what is the reason ?

**Comment by scxiao** [comment] 2021-06-16 16:37
@qianqing13579 I cannot reproduce the problem, so no idea what is the reason..
Can you try the latest develop branch to see whether it works for you now?

**Comment by qianqing13579** [comment] 2021-06-17 00:30
@scxiao ，I tried the latest develop branch, it works well. Thanks

**Comment by scxiao** [comment] 2021-06-17 03:01
issue is not reproducible, so close this issue.

**Closed by scxiao** 2021-06-17 03:01 UTC
