### ISSUE TITLE
DistilBert: Missing operators

### ISSUE THREAD

**Issue by kahmed10** [ROCmSoftwarePlatform/AMDMIGraphX#593] opened 2020-07-29 16:31 UTC
- Expand
- Equal
- Where

**Comment by scxiao** [comment] 2020-07-29 21:52
We have a parse_expand for onnx models

**Comment by scxiao** [comment] 2020-07-29 21:52
Maybe only limited support for Expand

**Comment by scxiao** [comment] 2020-08-31 14:56
With the bool type and equal operator added, only the where operator is not supported now.

**Comment by scxiao** [comment] 2020-09-08 21:35
After where operator is added, MIGraphX can run the whole model now. But all the result values are nan, not sure what is the reason.

**Comment by scxiao** [comment] 2020-09-25 15:34
Looks like we did not pass the constant operator correctly. The constant value uses a raw buffer for float, but the values are inf or nan. One example is: If

**Comment by scxiao** [comment] 2020-09-25 15:46
it also could be we did not handle the inf value in correct way.

**Comment by scxiao** [comment] 2020-09-28 14:58
I wrote a python script that can convert the value tensor to a numpy array, in this way, we can print out both the raw data content and the actual value corresponding to the raw data, looks like our parsing of those values is correct. So it looks like the program is how we handling values like -inf and nan. 

I also run this model in ORT with the CPU EP, the outputs are reasonable values.

**Comment by scxiao** [comment] 2020-09-28 16:08
I just tried this model in the tensorrt and CUDA EP, their results are correct. One observation is the CUDA EP reported a bunch of operators fall back to the CPU, here is the specific information:
[distilbert_cuda_out.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/5293621/distilbert_cuda_out.txt)

**Comment by scxiao** [comment] 2020-09-29 00:51
Just downloaded another pretrained distilbert model, and the constant is also -inf in some cases.

**Comment by scxiao** [comment] 2020-11-03 17:28
Some update:
The inf issue causes a problem for our Where OP implementation. Specifically, we use the following formulation to achieve where op: output = cond * (x - y) + y. For this formula, when cond == 1, we get x; and when cond == 0, we get y. This formula works well for normal numbers, but if either x or y is inf or nan, we have a problem. 

In the distill_bert model, x is inf and cond is always 0, so the output should be y. But if we use the above formula do the computation, we have problem.

**Comment by scxiao** [comment] 2020-11-03 21:28
I just manually change the -inf to 1.0 when parsing the model (the -inf is not actually used in the model), then migraphx can achieve the same results that the CPU EP in onnxruntime. So we can confirm that the nan output is caused by our where op implementation cannot handle the inf value.

**Comment by scxiao** [comment] 2020-11-11 16:57
PR #676 is created to fix the above issue.

**Comment by scxiao** [comment] 2020-12-03 19:50
Issue fixed and close it

**Closed by scxiao** 2020-12-03 19:50 UTC
