### ISSUE TITLE
Resolve the "dynamic shape" issue related to AvgPool/MaxPool when parsing image models

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#410] opened 2019-12-18 22:12 UTC
MIGRAPHX can support the AvgPool/MaxPool operators in the current image models, but cannot support them passed from the onnxruntime. The reason is onnxruntime upgrade the model to opset 11, in which AvgPool/MaxPool has a dynamic shape input. 

This task is to resolve the above issue related to dynamic shape input in AvgPool/MaxPool.

**Comment by scxiao** [comment] 2020-01-14 05:31
With the latest changes in both onnxruntime and migraphx, all pooling operators can run in migraphx, so imagenet model has very small overhead running on onnxruntime with mgiraphx as the backend compared to running in migraphx directly. 

But there are still modes of both maxpool and averagepool that migraphx cannot handle, and we might need to improve the miopen pooling function.

**Comment by mvermeulen** [comment] 2020-03-11 19:53
Duplicate of issue #412

**Closed by mvermeulen** 2020-03-11 19:53 UTC
Labels: onnxruntime
